---
daemonset:
  enabled: true
  filebeatConfig:
    filebeat.yml: |
      filebeat.autodiscover:
        providers:
          - type: kubernetes
            hints.enabled: true
            hints.default_config:
              type: container
              paths:
                - /var/lib/docker/containers/${data.kubernetes.container.id}/*.log
      output.elasticsearch:
        host: '${NODE_NAME}'
        hosts: 'elasticsearch-coordinating-only.elasticsearch.svc.cluster.local:9200'
