---
daemonset:
  filebeatConfig:
    filebeat.yml: |
      filebeat.autodiscover:
        providers:
          - type: kubernetes
            hints.enabled: true
            hints.default_config:
              type: container
              paths:
                - /var/lib/docker/containers/${data.kubernetes.container.id}/*.log
      cloud.id: "cloud-id-token-goes-here"
      cloud.auth: "cloud-auth-goes-here"
