kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-config
  namespace: nginx-ingress
data:
  log-format: $remote_addr - $remote_user [$time_local] "$request" $status $body_bytes_sent
    "$http_referer" "$http_user_agent" $upstream_response_time $upstream_status "$uri"
    $request_length $request_time [$proxy_host] [] $upstream_addr $upstream_bytes_sent
    $upstream_response_time $upstream_status $request_id
