---
  controller: 
    kind: "deployment"
    nginxplus: true
    appprotect: 
      enable: false
    image: 
      repository: "register.virington.com/nginx-ingress"
      tag: "1.11.1"
      pullPolicy: "IfNotPresent"
    config:
      name: nginx-config
      annotations: {}
      entries: {"log-format": "$remote_addr - $remote_user [$time_local] \"$request\" $status $body_bytes_sent \"$http_referer\" \"$http_user_agent\" $upstream_response_time $upstream_status \"$uri\" $request_length $request_time [$proxy_host] [] $upstream_addr $upstream_bytes_sent $upstream_response_time $upstream_status $request_id"}
    serviceAccount: 
      imagePullSecretName: "register-secret"
    defaultTLS: 
      secret: ""
    ingressClass: "nginx"
    useIngressClassOnly: false
    enableCustomResources: true
    globalConfiguration: 
      create: true
    watchNamespace: ""
    service: 
      create: true
      type: "LoadBalancer"
      annotations: {"co.elastic.logs/module": "nginx"}
      httpPort: 
        enable: true
        port: "80"
      httpsPort: 
        enable: true
        port: "443"
    pod:
      annotations: {"co.elastic.logs/module": "nginx"}
  imageDefault: true
  prometheus: 
    create: true
    port: "9113"
